/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKeluarga;
import Controller.ControllerProfil;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class ViewProfile extends javax.swing.JFrame {
    private int id_user;
    ControllerProfil cf;
    ControllerKeluarga ck;
    
    /**
     * Creates new form Profile
     */
    public ViewProfile(int id) {
        this.id_user = id;
        initComponents();
        cf = new ControllerProfil(this, id);
        ck = new ControllerKeluarga(this, id);
        
        cf.isiForm();
        cf.isiFormAlamat();
        ck.isiKeluarga();
        ck.isiAnggota();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneProfile = new javax.swing.JTabbedPane();
        panelProfile = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelProv = new javax.swing.JLabel();
        labelTgl = new javax.swing.JLabel();
        inputNamaProfil = new javax.swing.JTextField();
        inputTtlProfil = new javax.swing.JTextField();
        inputProvinsi = new javax.swing.JTextField();
        labelKota = new javax.swing.JLabel();
        inputKota = new javax.swing.JTextField();
        labelKabKot = new javax.swing.JLabel();
        inputKabKot = new javax.swing.JTextField();
        labelKecamatan = new javax.swing.JLabel();
        inputKecamatan = new javax.swing.JTextField();
        labelKelurahan = new javax.swing.JLabel();
        inputKelurahan = new javax.swing.JTextField();
        labelAlamat4 = new javax.swing.JLabel();
        inputRT = new javax.swing.JTextField();
        labelAlamat5 = new javax.swing.JLabel();
        inputRW = new javax.swing.JTextField();
        labelAlamat6 = new javax.swing.JLabel();
        inputNoRumah = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panelAnggotaKeluarga = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAnggotaKeluarga = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        labelIdKeluarga = new javax.swing.JLabel();
        inputTglLahirAnggotaKeluarga = new javax.swing.JTextField();
        inputKotaLahirAnggotaKeluarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        inputNamaAnggotaKeluarga = new javax.swing.JTextField();
        btnTambahAnggota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedPaneProfile.setName(""); // NOI18N

        labelNama.setText("Nama :");

        labelProv.setText("Provinsi :");

        labelTgl.setText("Tanggal Lahir :");

        labelKota.setText("Kota Lahir :");

        labelKabKot.setText("Kab/Kota :");

        labelKecamatan.setText("Kecamatan :");

        labelKelurahan.setText("Kelurahan :");

        labelAlamat4.setText("RT :");

        labelAlamat5.setText("RW :");

        labelAlamat6.setText("Nomor Rumah :");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Kembali");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat6)
                    .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                            .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNama)
                                .addComponent(labelTgl)
                                .addComponent(labelProv)
                                .addComponent(labelKota)
                                .addComponent(labelKecamatan))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelProfileLayout.createSequentialGroup()
                            .addComponent(labelAlamat4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputKota, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTtlProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNamaProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelProfileLayout.createSequentialGroup()
                                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputRT, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelProfileLayout.createSequentialGroup()
                                        .addComponent(labelAlamat5)
                                        .addGap(58, 58, 58)
                                        .addComponent(inputRW, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelKelurahan)
                                        .addGroup(panelProfileLayout.createSequentialGroup()
                                            .addComponent(labelKabKot)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(inputKabKot, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                            .addComponent(inputKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(inputKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelProfileLayout.createSequentialGroup()
                        .addComponent(inputNoRumah, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(inputNamaProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKota)
                    .addComponent(inputKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTgl)
                    .addComponent(inputTtlProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProv)
                    .addComponent(inputProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKabKot)
                    .addComponent(inputKabKot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKecamatan)
                    .addComponent(inputKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKelurahan))
                .addGap(24, 24, 24)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamat4)
                    .addComponent(inputRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat5))
                .addGap(18, 18, 18)
                .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAlamat6)
                        .addComponent(inputNoRumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(btnBack)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabbedPaneProfile.addTab("Profile", panelProfile);

        jLabel2.setText("id Keluarga:");

        jScrollPane1.setViewportView(listAnggotaKeluarga);

        jLabel3.setText("Anggota keluarga:");

        labelIdKeluarga.setText("id_keluarga");

        jLabel10.setText("Nama:");

        jLabel12.setText("Tanggal Lahir:");

        jLabel13.setText("Kota Lahir:");

        btnTambahAnggota.setText("Tambah");
        btnTambahAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahAnggotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAnggotaKeluargaLayout = new javax.swing.GroupLayout(panelAnggotaKeluarga);
        panelAnggotaKeluarga.setLayout(panelAnggotaKeluargaLayout);
        panelAnggotaKeluargaLayout.setHorizontalGroup(
            panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputNamaAnggotaKeluarga)
                                    .addComponent(inputTglLahirAnggotaKeluarga)
                                    .addComponent(inputKotaLahirAnggotaKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTambahAnggota))))
                    .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                        .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdKeluarga)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        panelAnggotaKeluargaLayout.setVerticalGroup(
            panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelIdKeluarga))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAnggotaKeluargaLayout.createSequentialGroup()
                        .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(inputNamaAnggotaKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(inputTglLahirAnggotaKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelAnggotaKeluargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(inputKotaLahirAnggotaKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnTambahAnggota)))
                .addGap(27, 27, 27))
        );

        tabbedPaneProfile.addTab("Anggota Keluarga", panelAnggotaKeluarga);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneProfile, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabbedPaneProfile.getAccessibleContext().setAccessibleName("Show");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewDashboard(id_user).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        cf.updateProfil();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTambahAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahAnggotaActionPerformed
        // TODO add your handling code here:
        ck.addAnggota();
    }//GEN-LAST:event_btnTambahAnggotaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewProfile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTambahAnggota;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField inputKabKot;
    private javax.swing.JTextField inputKecamatan;
    private javax.swing.JTextField inputKelurahan;
    private javax.swing.JTextField inputKota;
    private javax.swing.JTextField inputKotaLahirAnggotaKeluarga;
    private javax.swing.JTextField inputNamaAnggotaKeluarga;
    private javax.swing.JTextField inputNamaProfil;
    private javax.swing.JTextField inputNoRumah;
    private javax.swing.JTextField inputProvinsi;
    private javax.swing.JTextField inputRT;
    private javax.swing.JTextField inputRW;
    private javax.swing.JTextField inputTglLahirAnggotaKeluarga;
    private javax.swing.JTextField inputTtlProfil;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamat4;
    private javax.swing.JLabel labelAlamat5;
    private javax.swing.JLabel labelAlamat6;
    private javax.swing.JLabel labelIdKeluarga;
    private javax.swing.JLabel labelKabKot;
    private javax.swing.JLabel labelKecamatan;
    private javax.swing.JLabel labelKelurahan;
    private javax.swing.JLabel labelKota;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelProv;
    private javax.swing.JLabel labelTgl;
    private javax.swing.JList<String> listAnggotaKeluarga;
    private javax.swing.JPanel panelAnggotaKeluarga;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JTabbedPane tabbedPaneProfile;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getInputNamaProfil() {
        return inputNamaProfil;
    }
    
    public void setInputNamaProfil(JTextField inputNamaProfil) {
        this.inputNamaProfil = inputNamaProfil;
    }
    
    public JTextField getInputKota() {
        return inputKota;
    }
    
    public void setInputKota(JTextField inputKota) {
        this.inputKota = inputKota;
    }
    
    public JTextField getInputTtlProfil() {
        return inputTtlProfil;
    }
    
    public void setInputTtlProfil(JTextField inputTtlProfil) {
        this.inputTtlProfil = inputTtlProfil;
    }
    
    public JTextField getInputProvinsi() {
        return inputProvinsi;
    }
    
    public void setInputProvinsi(JTextField inputProvinsi) {
        this.inputProvinsi = inputProvinsi;
    }
    
    public JTextField getInputKabKot() {
        return inputKabKot;
    }
    
    public void setInputKabKot(JTextField inputKabKot) {
        this.inputKabKot = inputKabKot;
    }
    
    public JTextField getInputRT() {
        return inputRT;
    }
    
    public void setInputRT(JTextField inputRT) {
        this.inputRT = inputRT;
    }
    
    public JTextField getInputRW() {
        return inputRW;
    }
    
    public void setInputRW(JTextField inputRW) {
        this.inputRW = inputRW;
    }
    
    public JTextField getInputKelurahan() {
        return inputKelurahan;
    }
    
    public void setInputKelurahan(JTextField inputKelurahan) {
        this.inputKelurahan = inputKelurahan;
    }
    
    public JTextField getInputKecamatan() {
        return inputKecamatan;
    }
    
    public void setInputKecamatan(JTextField inputKecamatan) {
        this.inputKecamatan = inputKecamatan;
    }
    
    public JTextField getInputNoRumah() {
        return inputNoRumah;
    }
    
    public void setInputNoRumah(JTextField inputNoRumah) {
        this.inputNoRumah = inputNoRumah;
    }
    
    public JLabel getLabelIdKeluarga() {
        return labelIdKeluarga;
    }
    
    public JTextField getInputNamaAnggota() {
        return inputNamaAnggotaKeluarga;
    }
    
    public void setInputNamaAnggota(JTextField inputNamaAnggotaKeluarga) {
        this.inputNamaAnggotaKeluarga = inputNamaAnggotaKeluarga;
    }
    
    public JTextField getInputTglAnggota() {
        return inputTglLahirAnggotaKeluarga;
    }
    
    public void setInputTglAnggota(JTextField inputTglLahirAnggotaKeluarga) {
        this.inputTglLahirAnggotaKeluarga = inputTglLahirAnggotaKeluarga;
    }
            
    public JTextField getInputKotaAnggota() {
        return inputKotaLahirAnggotaKeluarga;
    }
    
    public void setInputKotaAnggota(JTextField inputKotaLahirAnggotaKeluarga) {
        this.inputKotaLahirAnggotaKeluarga = inputKotaLahirAnggotaKeluarga;
    }
    
    public JList getListAnggota() {
        return listAnggotaKeluarga;
    }
    
    public void setListAnggota(JList listAnggotaKeluarga) {
        this.listAnggotaKeluarga = listAnggotaKeluarga;
    }
}
