/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerKebutuhan;
import Controller.ControllerPengungsian;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Sabre
 */
public class ViewDashboard extends javax.swing.JFrame {
    private int id_user;
    ControllerPengungsian cp;
    ControllerKebutuhan ck;
    
    /**
     * Creates new form Dashboard
     */
    public ViewDashboard(int id) {
        this.id_user = id;
        initComponents();
        cp = new ControllerPengungsian(this);
        ck = new ControllerKebutuhan(this);
        
        cp.isiTabel();
        ck.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_DataPengungsian = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDaftarPengungsian = new javax.swing.JTable();
        lblNamaTempat = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblKapasitas = new javax.swing.JLabel();
        inputNamaTempat = new javax.swing.JTextField();
        inputAlamat = new javax.swing.JTextField();
        inputKapasitas = new javax.swing.JTextField();
        btnTambahDataPengungsian = new javax.swing.JButton();
        btnUbahDataPengungsian = new javax.swing.JButton();
        btnHapusDataPengungsian = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDaftarKebutuhan = new javax.swing.JTable();
        lblKeluarga = new javax.swing.JLabel();
        lblNamaBarang = new javax.swing.JLabel();
        lblSatuanKebutuhan = new javax.swing.JLabel();
        lblJumlahKebutuhan = new javax.swing.JLabel();
        lblKebutuhanPokok = new javax.swing.JLabel();
        inputKeluarga = new javax.swing.JTextField();
        inputNamaBarang = new javax.swing.JTextField();
        inputSatuanKebutuhan = new javax.swing.JTextField();
        inputJumlahKebutuhan = new javax.swing.JTextField();
        checkKebutuhanPokok = new javax.swing.JCheckBox();
        btnTambahDataKebutuhan = new javax.swing.JButton();
        btnUbahDataKebutuhan = new javax.swing.JButton();
        btnHapusDataKebutuhan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDataObat = new javax.swing.JTable();
        lblIdObat = new javax.swing.JLabel();
        lblPenyakit = new javax.swing.JLabel();
        lblNamaObat = new javax.swing.JLabel();
        lblSatuanObat = new javax.swing.JLabel();
        lblJumlahObat = new javax.swing.JLabel();
        inputIdObat = new javax.swing.JTextField();
        inputPenyakit = new javax.swing.JTextField();
        inputNamaObat = new javax.swing.JTextField();
        inputSatuanObat = new javax.swing.JTextField();
        inputJumlahObat = new javax.swing.JTextField();
        btnTambahDataObat = new javax.swing.JButton();
        btnUbahDataObat = new javax.swing.JButton();
        btnHapusDataObat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDataPenyakit = new javax.swing.JTable();
        lblIdPenyakit = new javax.swing.JLabel();
        lblNamaPenyakit = new javax.swing.JLabel();
        lblPenyandang = new javax.swing.JLabel();
        inputIdPenyakit = new javax.swing.JTextField();
        inputNamaPenyakit = new javax.swing.JTextField();
        inputPenyandang = new javax.swing.JTextField();
        btnTambahDataPenyakit = new javax.swing.JButton();
        btnUbahDataPenyakit = new javax.swing.JButton();
        btnHapusDataPenyakit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        tableDaftarPengungsian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Pengungsian", "Nama Tempat", "Alamat", "Kapasitas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDaftarPengungsian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableDaftarPengungsian.setGridColor(new java.awt.Color(0, 0, 204));
        tableDaftarPengungsian.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tableDaftarPengungsian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDaftarPengungsianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDaftarPengungsian);

        lblNamaTempat.setText("Nama Tempat");

        lblAlamat.setText("Alamat");

        lblKapasitas.setText("Kapasitas");

        inputNamaTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaTempatActionPerformed(evt);
            }
        });

        btnTambahDataPengungsian.setText("Tambah");
        btnTambahDataPengungsian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDataPengungsianActionPerformed(evt);
            }
        });

        btnUbahDataPengungsian.setText("Ubah");

        btnHapusDataPengungsian.setText("Hapus");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlamat)
                            .addComponent(lblNamaTempat)
                            .addComponent(lblKapasitas))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNamaTempat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputKapasitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambahDataPengungsian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUbahDataPengungsian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapusDataPengungsian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaTempat)
                    .addComponent(inputNamaTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahDataPengungsian))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamat)
                    .addComponent(btnUbahDataPengungsian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKapasitas)
                    .addComponent(inputKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusDataPengungsian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPane_DataPengungsian.addTab("Data Pengungsian", jPanel1);

        tableDaftarKebutuhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Kebutuhan", "Keluarga", "Nama Barang", "Satuan", "Jumlah", "Kebutuhan Pokok / Bukan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDaftarKebutuhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDaftarKebutuhanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDaftarKebutuhan);

        lblKeluarga.setText("Keluarga");

        lblNamaBarang.setText("Nama Barang");

        lblSatuanKebutuhan.setText("Satuan");

        lblJumlahKebutuhan.setText("Jumlah");

        lblKebutuhanPokok.setText("Kebutuhan Pokok");

        btnTambahDataKebutuhan.setText("Tambah");

        btnUbahDataKebutuhan.setText("Ubah");

        btnHapusDataKebutuhan.setText("Hapus");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKeluarga)
                    .addComponent(lblNamaBarang))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(inputKeluarga))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJumlahKebutuhan)
                            .addComponent(lblSatuanKebutuhan))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSatuanKebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputJumlahKebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblKebutuhanPokok)
                        .addGap(18, 18, 18)
                        .addComponent(checkKebutuhanPokok)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambahDataKebutuhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbahDataKebutuhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusDataKebutuhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSatuanKebutuhan)
                    .addComponent(inputSatuanKebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahDataKebutuhan)
                    .addComponent(inputKeluarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeluarga))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJumlahKebutuhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahDataKebutuhan)
                    .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaBarang)
                    .addComponent(lblJumlahKebutuhan))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapusDataKebutuhan)
                    .addComponent(checkKebutuhanPokok)
                    .addComponent(lblKebutuhanPokok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jTabbedPane_DataPengungsian.addTab("Data Kebutuhan", jPanel2);

        tableDataObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_Obat", "Penyakit", "Nama Obat", "Satuan", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDataObat);

        lblIdObat.setText("Id_Obat");

        lblPenyakit.setText("Penyakit");

        lblNamaObat.setText("Nama Obat");

        lblSatuanObat.setText("Satuan");

        lblJumlahObat.setText("Jumlah");

        btnTambahDataObat.setText("Tambah");

        btnUbahDataObat.setText("Ubah");

        btnHapusDataObat.setText("Hapus");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdObat)
                    .addComponent(lblPenyakit)
                    .addComponent(lblNamaObat))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(inputPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblJumlahObat))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(inputIdObat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lblSatuanObat)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSatuanObat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputJumlahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(inputNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHapusDataObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbahDataObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahDataObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIdObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSatuanObat)
                    .addComponent(inputSatuanObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdObat)
                    .addComponent(btnTambahDataObat))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPenyakit)
                    .addComponent(inputPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputJumlahObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlahObat)
                    .addComponent(btnUbahDataObat))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaObat)
                    .addComponent(inputNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusDataObat))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane_DataPengungsian.addTab("Data Obat", jPanel3);

        tableDataPenyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id_Penyakit", "Nama Penyakit", "Penyandang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableDataPenyakit);

        lblIdPenyakit.setText("Id_Penyakit");

        lblNamaPenyakit.setText("Nama Penyakit");

        lblPenyandang.setText("Penyandang");

        inputPenyandang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPenyandangActionPerformed(evt);
            }
        });

        btnTambahDataPenyakit.setText("Tambah");

        btnUbahDataPenyakit.setText("Ubah");

        btnHapusDataPenyakit.setText("Hapus");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdPenyakit)
                    .addComponent(lblNamaPenyakit)
                    .addComponent(lblPenyandang))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputNamaPenyakit)
                    .addComponent(inputIdPenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(inputPenyandang))
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTambahDataPenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbahDataPenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusDataPenyakit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPenyakit)
                    .addComponent(inputIdPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahDataPenyakit))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbahDataPenyakit)
                    .addComponent(inputNamaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaPenyakit))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPenyandang)
                    .addComponent(inputPenyandang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusDataPenyakit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane_DataPengungsian.addTab("Data Penyakit", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Profil");

        jMenuItem1.setText("Ubah Profil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_DataPengungsian)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane_DataPengungsian, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void inputPenyandangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPenyandangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPenyandangActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewProfile(id_user).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void inputNamaTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaTempatActionPerformed

    private void tableDaftarPengungsianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDaftarPengungsianMouseClicked
        // TODO add your handling code here:
        cp.isiTextField(tableDaftarPengungsian.getSelectedRow());
    }//GEN-LAST:event_tableDaftarPengungsianMouseClicked

    private void tableDaftarKebutuhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDaftarKebutuhanMouseClicked
        // TODO add your handling code here:
        ck.isiTextField(tableDaftarKebutuhan.getSelectedRow());
    }//GEN-LAST:event_tableDaftarKebutuhanMouseClicked

    private void btnTambahDataPengungsianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDataPengungsianActionPerformed
        
    }//GEN-LAST:event_btnTambahDataPengungsianActionPerformed


    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewDashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusDataKebutuhan;
    private javax.swing.JButton btnHapusDataObat;
    private javax.swing.JButton btnHapusDataPengungsian;
    private javax.swing.JButton btnHapusDataPenyakit;
    private javax.swing.JButton btnTambahDataKebutuhan;
    private javax.swing.JButton btnTambahDataObat;
    private javax.swing.JButton btnTambahDataPengungsian;
    private javax.swing.JButton btnTambahDataPenyakit;
    private javax.swing.JButton btnUbahDataKebutuhan;
    private javax.swing.JButton btnUbahDataObat;
    private javax.swing.JButton btnUbahDataPengungsian;
    private javax.swing.JButton btnUbahDataPenyakit;
    private javax.swing.JCheckBox checkKebutuhanPokok;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputIdObat;
    private javax.swing.JTextField inputIdPenyakit;
    private javax.swing.JTextField inputJumlahKebutuhan;
    private javax.swing.JTextField inputJumlahObat;
    private javax.swing.JTextField inputKapasitas;
    private javax.swing.JTextField inputKeluarga;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JTextField inputNamaObat;
    private javax.swing.JTextField inputNamaPenyakit;
    private javax.swing.JTextField inputNamaTempat;
    private javax.swing.JTextField inputPenyakit;
    private javax.swing.JTextField inputPenyandang;
    private javax.swing.JTextField inputSatuanKebutuhan;
    private javax.swing.JTextField inputSatuanObat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane_DataPengungsian;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblIdObat;
    private javax.swing.JLabel lblIdPenyakit;
    private javax.swing.JLabel lblJumlahKebutuhan;
    private javax.swing.JLabel lblJumlahObat;
    private javax.swing.JLabel lblKapasitas;
    private javax.swing.JLabel lblKebutuhanPokok;
    private javax.swing.JLabel lblKeluarga;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblNamaObat;
    private javax.swing.JLabel lblNamaPenyakit;
    private javax.swing.JLabel lblNamaTempat;
    private javax.swing.JLabel lblPenyakit;
    private javax.swing.JLabel lblPenyandang;
    private javax.swing.JLabel lblSatuanKebutuhan;
    private javax.swing.JLabel lblSatuanObat;
    private javax.swing.JTable tableDaftarKebutuhan;
    private javax.swing.JTable tableDaftarPengungsian;
    private javax.swing.JTable tableDataObat;
    private javax.swing.JTable tableDataPenyakit;
    // End of variables declaration//GEN-END:variables
    
    public JTextField getInputNamaTempat() {
        return inputNamaTempat;
    }
    
    public void setInputNamaTempat(JTextField inputNamaTempat) {
        this.inputNamaTempat = inputNamaTempat;
    }
    
    public JTextField getInputAlamat() {
        return inputAlamat;
    }
    
    public void setInputAlamat(JTextField inputAlamat) {
        this.inputAlamat = inputAlamat;
    }
    
    public JTextField getInputKapasitas() {
        return inputKapasitas;
    }
    
    public void setInputKapasitas(JTextField inputKapasitas) {
        this.inputKapasitas = inputKapasitas;
    }
    
    public JTable getTablePengungsian() {
        return tableDaftarPengungsian;
    }
    
    public void setTablePengungsian(JTable tableDaftarPengungsian) {
        this.tableDaftarPengungsian = tableDaftarPengungsian;
    }
    
    public JTextField getInputKeluarga() {
        return inputKeluarga;
    }
    
    public void setInputKeluarga(JTextField inputKeluarga) {
        this.inputKeluarga = inputKeluarga;
    }
    
    public JTextField getInputSatuanKebutuhan() {
        return inputSatuanKebutuhan;
    }
    
    public void setInputSatuanKebutuhan(JTextField inputSatuanKebutuhan) {
        this.inputSatuanKebutuhan = inputSatuanKebutuhan;
    }
    
    public JTextField getInputNamaBarang() {
        return inputNamaBarang;
    }
    
    public void setInputNamaBarang(JTextField inputNamaBarang) {
        this.inputNamaBarang = inputNamaBarang;
    }
    
    public JTextField getInputJumlahKebutuhan() {
        return inputJumlahKebutuhan;
    }
    
    public void setInputJumlahKebutuhan(JTextField inputJumlahKebutuhan) {
        this.inputJumlahKebutuhan = inputJumlahKebutuhan;
    }
    
    public JCheckBox getcheckKebutuhanPokok() {
        return checkKebutuhanPokok;
    }
    
    public void setcheckKebutuhanPokok(JCheckBox checkKebutuhanPokok) {
        this.checkKebutuhanPokok = checkKebutuhanPokok;
    }
    
    public JTable getTableKebutuhan() {
        return tableDaftarKebutuhan;
    }
    
    public void setTableKebutuhan(JTable tableDaftarKebutuhan) {
        this.tableDaftarKebutuhan = tableDaftarKebutuhan;
    }
}
